<?php

/**
 * BaseSurveyGefallen
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property enum $preislich
 * @property enum $spontan
 * @property enum $gutes_angebot
 * @property enum $freunden
 * @property enum $entfernung
 * @property enum $junge
 * @property integer $user_id
 * @property User $User
 * 
 * @method integer        getId()            Returns the current record's "id" value
 * @method enum           getPreislich()     Returns the current record's "preislich" value
 * @method enum           getSpontan()       Returns the current record's "spontan" value
 * @method enum           getGutesAngebot()  Returns the current record's "gutes_angebot" value
 * @method enum           getFreunden()      Returns the current record's "freunden" value
 * @method enum           getEntfernung()    Returns the current record's "entfernung" value
 * @method enum           getJunge()         Returns the current record's "junge" value
 * @method integer        getUserId()        Returns the current record's "user_id" value
 * @method User           getUser()          Returns the current record's "User" value
 * @method SurveyGefallen setId()            Sets the current record's "id" value
 * @method SurveyGefallen setPreislich()     Sets the current record's "preislich" value
 * @method SurveyGefallen setSpontan()       Sets the current record's "spontan" value
 * @method SurveyGefallen setGutesAngebot()  Sets the current record's "gutes_angebot" value
 * @method SurveyGefallen setFreunden()      Sets the current record's "freunden" value
 * @method SurveyGefallen setEntfernung()    Sets the current record's "entfernung" value
 * @method SurveyGefallen setJunge()         Sets the current record's "junge" value
 * @method SurveyGefallen setUserId()        Sets the current record's "user_id" value
 * @method SurveyGefallen setUser()          Sets the current record's "User" value
 * 
 * @package    bahn
 * @subpackage model
 * @author     Marco Schierhorn
 * @version    SVN: $Id$
 */
abstract class BaseSurveyGefallen extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('survey_gefallen');
        $this->hasColumn('id', 'integer', 6, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 6,
             ));
        $this->hasColumn('preislich', 'enum', null, array(
             'type' => 'enum',
             'notnull' => true,
             'values' => 
             array(
              0 => 5,
              1 => 4,
              2 => 3,
              3 => 2,
              4 => 1,
              5 => 98,
             ),
             ));
        $this->hasColumn('spontan', 'enum', null, array(
             'type' => 'enum',
             'notnull' => true,
             'values' => 
             array(
              0 => 5,
              1 => 4,
              2 => 3,
              3 => 2,
              4 => 1,
              5 => 98,
             ),
             ));
        $this->hasColumn('gutes_angebot', 'enum', null, array(
             'type' => 'enum',
             'notnull' => true,
             'values' => 
             array(
              0 => 5,
              1 => 4,
              2 => 3,
              3 => 2,
              4 => 1,
              5 => 98,
             ),
             ));
        $this->hasColumn('freunden', 'enum', null, array(
             'type' => 'enum',
             'notnull' => true,
             'values' => 
             array(
              0 => 5,
              1 => 4,
              2 => 3,
              3 => 2,
              4 => 1,
              5 => 98,
             ),
             ));
        $this->hasColumn('entfernung', 'enum', null, array(
             'type' => 'enum',
             'notnull' => true,
             'values' => 
             array(
              0 => 5,
              1 => 4,
              2 => 3,
              3 => 2,
              4 => 1,
              5 => 98,
             ),
             ));
        $this->hasColumn('junge', 'enum', null, array(
             'type' => 'enum',
             'notnull' => true,
             'values' => 
             array(
              0 => 5,
              1 => 4,
              2 => 3,
              3 => 2,
              4 => 1,
              5 => 98,
             ),
             ));
        $this->hasColumn('user_id', 'integer', 6, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 6,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));
    }
}