<?php

/**
 * BaseStandorte
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property User $UserModel
 * 
 * @method integer   getId()        Returns the current record's "id" value
 * @method string    getName()      Returns the current record's "name" value
 * @method User      getUserModel() Returns the current record's "UserModel" value
 * @method Standorte setId()        Sets the current record's "id" value
 * @method Standorte setName()      Sets the current record's "name" value
 * @method Standorte setUserModel() Sets the current record's "UserModel" value
 * 
 * @package    bahn
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id$
 */
abstract class BaseStandorte extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('standorte');
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User as UserModel', array(
             'local' => 'id',
             'foreign' => 'standorte_id'));
    }
}