<?php

/**
 * BaseCodes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property boolean $used
 * @property User $User
 * 
 * @method integer getId()   Returns the current record's "id" value
 * @method string  getName() Returns the current record's "name" value
 * @method boolean getUsed() Returns the current record's "used" value
 * @method User    getUser() Returns the current record's "User" value
 * @method Codes   setId()   Sets the current record's "id" value
 * @method Codes   setName() Sets the current record's "name" value
 * @method Codes   setUsed() Sets the current record's "used" value
 * @method Codes   setUser() Sets the current record's "User" value
 * 
 * @package    bahn
 * @subpackage model
 * @author     Marco Schierhorn
 * @version    SVN: $Id$
 */
abstract class BaseCodes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('codes');
        $this->hasColumn('id', 'integer', 6, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 6,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('used', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'id',
             'foreign' => 'codes_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}