<?php

/**
 * BaseSurveyAngebotVerkehrsmittel12User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $survey_id
 * @property integer $user_id
 * 
 * @method integer                           getSurveyId()  Returns the current record's "survey_id" value
 * @method integer                           getUserId()    Returns the current record's "user_id" value
 * @method SurveyAngebotVerkehrsmittel12User setSurveyId()  Sets the current record's "survey_id" value
 * @method SurveyAngebotVerkehrsmittel12User setUserId()    Sets the current record's "user_id" value
 * 
 * @package    bahn
 * @subpackage model
 * @author     Marco Schierhorn
 * @version    SVN: $Id$
 */
abstract class BaseSurveyAngebotVerkehrsmittel12User extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('survey_angebot_verkehrsmittel12_user');
        $this->hasColumn('survey_id', 'integer', 2, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 2,
             ));
        $this->hasColumn('user_id', 'integer', 6, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 6,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}