<?php

/**
 * BaseSurveyAngebotVerkehrsmittelAllgemein
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $User
 * 
 * @method integer                              getId()   Returns the current record's "id" value
 * @method string                               getName() Returns the current record's "name" value
 * @method Doctrine_Collection                  getUser() Returns the current record's "User" collection
 * @method SurveyAngebotVerkehrsmittelAllgemein setId()   Sets the current record's "id" value
 * @method SurveyAngebotVerkehrsmittelAllgemein setName() Sets the current record's "name" value
 * @method SurveyAngebotVerkehrsmittelAllgemein setUser() Sets the current record's "User" collection
 * 
 * @package    bahn
 * @subpackage model
 * @author     Marco Schierhorn
 * @version    SVN: $Id$
 */
abstract class BaseSurveyAngebotVerkehrsmittelAllgemein extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('survey_angebot_verkehrsmittel_allgemein');
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('User', array(
             'refClass' => 'SurveyAngebotVerkehrsmittelAllgemeinUser',
             'local' => 'survey_id',
             'foreign' => 'user_id'));
    }
}