<?php

/**
 * BaseSurveyAngebotVergleichbareReise
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Survey $SurveyAngebotVergleichbareReiseModel
 * 
 * @method integer                         getId()                                   Returns the current record's "id" value
 * @method string                          getName()                                 Returns the current record's "name" value
 * @method Survey                          getSurveyAngebotVergleichbareReiseModel() Returns the current record's "SurveyAngebotVergleichbareReiseModel" value
 * @method SurveyAngebotVergleichbareReise setId()                                   Sets the current record's "id" value
 * @method SurveyAngebotVergleichbareReise setName()                                 Sets the current record's "name" value
 * @method SurveyAngebotVergleichbareReise setSurveyAngebotVergleichbareReiseModel() Sets the current record's "SurveyAngebotVergleichbareReiseModel" value
 * 
 * @package    bahn
 * @subpackage model
 * @author     Marco Schierhorn
 * @version    SVN: $Id$
 */
abstract class BaseSurveyAngebotVergleichbareReise extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('survey_angebot_vergleichbare_reise');
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 2,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Survey as SurveyAngebotVergleichbareReiseModel', array(
             'local' => 'id',
             'foreign' => 'survey_angebot_vergleichbare_reise_id'));
    }
}