<?php

/**
 * Codes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bahn
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id$
 */
class Codes extends BaseCodes
{
}
