<?php

/**
 * CodesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CodesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CodesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Codes');
    }
}