<?php

/**
 * StandorteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StandorteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StandorteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Standorte');
    }
}