<?php

/**
 * SurveyAngebotVergleichbareReiseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SurveyAngebotVergleichbareReiseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SurveyAngebotVergleichbareReiseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SurveyAngebotVergleichbareReise');
    }
}