<?php

/**
 * SurveyAngebotBekanntTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SurveyAngebotBekanntTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SurveyAngebotBekanntTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SurveyAngebotBekannt');
    }
}