<?php

/**
 * SurveyAngebotVerkehrsmittelAllgemeinTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SurveyAngebotVerkehrsmittelAllgemeinTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SurveyAngebotVerkehrsmittelAllgemeinTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SurveyAngebotVerkehrsmittelAllgemein');
    }
}