<?php

/**
 * SurveyAngebotVerkehrsmittelAllgemeinUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SurveyAngebotVerkehrsmittelAllgemeinUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SurveyAngebotVerkehrsmittelAllgemeinUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SurveyAngebotVerkehrsmittelAllgemeinUser');
    }
}