<?php

/**
 * SurveyGefallenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SurveyGefallenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SurveyGefallenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SurveyGefallen');
    }
}