<?php

/**
 * SurveyAngebotVerkehrsmittel12Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SurveyAngebotVerkehrsmittel12Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SurveyAngebotVerkehrsmittel12Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SurveyAngebotVerkehrsmittel12');
    }
}