<?php

/**
 * SurveyAngebotVerkehrsmittel12UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SurveyAngebotVerkehrsmittel12UserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SurveyAngebotVerkehrsmittel12UserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SurveyAngebotVerkehrsmittel12User');
    }
}