<?php

/**
 * SurveyAnlaesseUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SurveyAnlaesseUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SurveyAnlaesseUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SurveyAnlaesseUser');
    }
}