<?php

/**
 * SurveyAngebotVerkehrsmittel12
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bahn
 * @subpackage model
 * @author     Marco Schierhorn
 * @version    SVN: $Id$
 */
class SurveyAngebotVerkehrsmittel12 extends BaseSurveyAngebotVerkehrsmittel12
{
}
