<?php

/**
 * SurveyAnlaesseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SurveyAnlaesseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SurveyAnlaesseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SurveyAnlaesse');
    }
}