<?php

/**
 * User
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    bahn
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id$
 */
class User extends BaseUser
{
  public function getFullName()
  {
    return $this->getVorname().' '.$this->getNachname();
  }

  public function getUserSecCode()
  {
    return md5($this->getEmail().$this->getCodes()->getName());
  }

  public function getName()
  {
    return $this->getVorname().' '.$this->getNachname();
  }
}
