<?php

/**
 * sfGuardForgotPassword
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bahn
 * @subpackage model
 * @author     Marco Schierhorn
 * @version    SVN: $Id$
 */
class sfGuardForgotPassword extends PluginsfGuardForgotPassword
{
}
