all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=dhw'
      username: dhw
      password: fhb7rb66Ys2MhzjL
prod:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=mysql5.webstars-online.de;dbname=db303872_2'
      username: db303872_2
      password: Stylo2010DHWBahn