generator:
  class: sfDoctrineGenerator
  param:
    model_class:           User
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:   
        title: User Management
        display: [anrede, Vorname, Nachname, Email, Strasse, Plz, Wohnort, Codes, Standorte, abgemeldet]
        sort: [created_at, desc]
        max_per_page: 10
      filter:  ~
      form:    ~
      edit:    
        title: Edit User "%%name%%"
      new:     
        title: Neuer User
